def Gangdam_Style
  puts "lower body"
  puts "1 Plant legs far apart, bend knees slightly and keep posture loose"
  puts "Lift right foot"
  puts "Return right foot to the ground"
  puts "Finishing with a small skip-step backward"
  puts "skip step left "
  puts "Lower left foot to the ground"
  puts "Bounce left foot back up slightly, kicking it a few inches back"
  puts "Left, Right, Left and Left"
  puts "Skip step right"
  puts "Lower right foot to the ground"
  puts "Bounce right foot back up slightly, kicking it a few inches back"
  puts "Right, Left, Right and Right"
  puts "Upper Body"
  puts "Bob The Reins"
  puts "Holding your arms out in front of you, straight and at chest level"
  puts "Cross your right wrist over your left and hold them together"
  puts "Lift your arms up and down in a loose bouncing movement, in time with the beat of the song. This movement is repeated eight times."
  puts "Lasso"
  puts "Start arm movement by holding left arm so the back of your wrist is near your chin, pointing your left elbow straight left."
  