def Gangdam_Style
  puts "lower body"
  puts "1 Plant legs far apart, bend knees slightly and keep posture loose"
  puts "Lift right foot"
  puts "Return right foot to the ground"
  puts "Finishing with a small skip-step backward"
  puts "skip step left "
  puts "Lower left foot to the ground"
  puts "Bounce left foot back up slightly, kicking it a few inches back"
  puts "Left, Right, Left and Left"
  puts "Skip step right"
  puts "Lower right foot to the ground"
  puts ""